import type { Metadata } from "next";
import { Inter, Sora } from "next/font/google";
import "./globals.css";

import TransitionProvider from "@/components/TransitionProvider";
import NavBar from "@/components/header/NavBar";
import TopLeftImg from "@/components/TopLeftImg";
import Header from "@/components/header/Header";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`page bg-site text-white bg-cover bg-no-repeat font-sora relative bg-[#2e2257] ${sora.variable}`}
      >

        <TopLeftImg />
        <Header />
        <TransitionProvider>
            {children}
        </TransitionProvider>
      </body>
    </html>
  );
}
